import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1780195796328 implements MigrationInterface {
    name = 'Init1780195796328'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`product_variants\` (\`id\` int NOT NULL AUTO_INCREMENT, \`sku\` varchar(100) NOT NULL, \`barcode\` varchar(100) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`cost_price\` decimal(10,2) NULL, \`original_price\` decimal(10,2) NOT NULL, \`discount_percent\` decimal(5,2) NOT NULL DEFAULT '0.00', \`sale_price\` decimal(10,2) NULL, \`sale_start_at\` timestamp NULL, \`sale_end_at\` timestamp NULL, \`stock\` int NOT NULL DEFAULT '0', \`reserved\` int NOT NULL DEFAULT '0', \`sold\` int NOT NULL DEFAULT '0', \`lowStockThreshold\` int NOT NULL DEFAULT '5', \`weight\` decimal(10,2) NULL, \`length\` decimal(10,2) NULL, \`width\` decimal(10,2) NULL, \`height\` decimal(10,2) NULL, \`imageThumbnail\` varchar(255) NULL, \`note\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`product_id\` int NULL, UNIQUE INDEX \`IDX_46f236f21640f9da218a063a86\` (\`sku\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` int NOT NULL, \`price\` decimal(10,2) NOT NULL, \`order_id\` int NULL, \`variant_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_status_history\` (\`id\` int NOT NULL AUTO_INCREMENT, \`status\` varchar(50) NOT NULL, \`note\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`order_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment_transactions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`payment_method\` varchar(50) NOT NULL, \`amount\` decimal(10,2) NOT NULL, \`status\` varchar(50) NOT NULL, \`transaction_code\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`order_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`orders\` (\`id\` int NOT NULL AUTO_INCREMENT, \`total_price\` decimal(10,2) NOT NULL, \`status\` varchar(50) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`user_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_sessions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`refreshToken\` varchar(255) NOT NULL, \`device\` varchar(255) NOT NULL, \`ip\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`avatarUrl\` varchar(255) NULL, \`public_id\` varchar(255) NULL, \`phone\` varchar(20) NULL, \`status\` enum ('active', 'suspended', 'invited', 'inactive') NOT NULL DEFAULT 'active', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`role_id\` int NULL, UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`wishlist\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NULL, \`product_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_d430a02aad006d8a70f3acd7d0\` ON \`role_permissions\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`assignedBy\` \`assignedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`roleId\` \`roleId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`permissionId\` \`permissionId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`shipping_addresses\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`category_translations\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`category_translations\` CHANGE \`category_id\` \`category_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`slug\` \`slug\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`parent_id\` \`parent_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_images\` CHANGE \`product_id\` \`product_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`review_images\` CHANGE \`review_id\` \`review_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` CHANGE \`comment\` \`comment\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` CHANGE \`product_id\` \`product_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_translations\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`product_translations\` CHANGE \`product_id\` \`product_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`brand_id\` \`brand_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`productCode\` \`productCode\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`verifyToken\` \`verifyToken\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`category_id\` \`category_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`country_id\` \`country_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`gender_id\` \`gender_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_attributes\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`attribute_value_images\` CHANGE \`public_id\` \`public_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`attribute_value_images\` CHANGE \`attribute_value_id\` \`attribute_value_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`attribute_id\` \`attribute_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`variant_attribute_values\` CHANGE \`variant_id\` \`variant_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`variant_attribute_values\` CHANGE \`attribute_value_id\` \`attribute_value_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`variant_images\` CHANGE \`variant_id\` \`variant_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`carts\` CHANGE \`guest_id\` \`guest_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`carts\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` CHANGE \`cart_id\` \`cart_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` CHANGE \`variant_id\` \`variant_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory_logs\` CHANGE \`reason\` \`reason\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory_logs\` CHANGE \`variant_id\` \`variant_id\` int NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_d430a02aad006d8a70f3acd7d0\` ON \`role_permissions\` (\`roleId\`, \`permissionId\`)`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_b4599f8b8f548d35850afa2d12c\` FOREIGN KEY (\`roleId\`) REFERENCES \`roles\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_06792d0c62ce6b0203c03643cdd\` FOREIGN KEY (\`permissionId\`) REFERENCES \`permissions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_addresses\` ADD CONSTRAINT \`FK_75ab21980cabc5be328df3e49cc\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category_translations\` ADD CONSTRAINT \`FK_87902f79e775e1c1b0082201d7e\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_88cea2dc9c31951d06437879b40\` FOREIGN KEY (\`parent_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_images\` ADD CONSTRAINT \`FK_4f166bb8c2bfcef2498d97b4068\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review_images\` ADD CONSTRAINT \`FK_45b8671ec9f03b6682a52adb120\` FOREIGN KEY (\`review_id\`) REFERENCES \`reviews\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_728447781a30bc3fcfe5c2f1cdf\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_9482e9567d8dcc2bc615981ef44\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_translations\` ADD CONSTRAINT \`FK_1b7b07c6049367c6446c5ac5605\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_9a5f6868c96e0069e699f33e124\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_1530a6f15d3c79d1b70be98f2be\` FOREIGN KEY (\`brand_id\`) REFERENCES \`brand\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_5c9f4d5bfcfed501870842f8339\` FOREIGN KEY (\`country_id\`) REFERENCES \`country\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_7d45aa29ba1109a087f0f6f19c2\` FOREIGN KEY (\`gender_id\`) REFERENCES \`gender\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_value_images\` ADD CONSTRAINT \`FK_873efe5d7f266ee50663fa68679\` FOREIGN KEY (\`attribute_value_id\`) REFERENCES \`attribute_values\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` ADD CONSTRAINT \`FK_be02d0f6a15bc7a0d835f832b62\` FOREIGN KEY (\`attribute_id\`) REFERENCES \`product_attributes\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`variant_attribute_values\` ADD CONSTRAINT \`FK_5df07e5f75117c9eca2c2ba5051\` FOREIGN KEY (\`variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`variant_attribute_values\` ADD CONSTRAINT \`FK_c714239ff4355d5e4dbfed5d196\` FOREIGN KEY (\`attribute_value_id\`) REFERENCES \`attribute_values\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`variant_images\` ADD CONSTRAINT \`FK_4006a994631d4bdb5938c831f39\` FOREIGN KEY (\`variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carts\` ADD CONSTRAINT \`FK_2ec1c94a977b940d85a4f498aea\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_6385a745d9e12a89b859bb25623\` FOREIGN KEY (\`cart_id\`) REFERENCES \`carts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_ede780fc2b865d1d1323e598038\` FOREIGN KEY (\`variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory_logs\` ADD CONSTRAINT \`FK_5132c139264f494991a44453746\` FOREIGN KEY (\`variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD CONSTRAINT \`FK_6343513e20e2deab45edfce1316\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_145532db85752b29c57d2b7b1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_db2d0ea722e16e0fe8ab3bce111\` FOREIGN KEY (\`variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_status_history\` ADD CONSTRAINT \`FK_1ca7d5228cf9dc589b60243933c\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_transactions\` ADD CONSTRAINT \`FK_0f581511ac19ecb02dab437cd41\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a922b820eeef29ac1c6800e826a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` ADD CONSTRAINT \`FK_55fa4db8406ed66bc7044328427\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_a2cecd1a3531c0b041e29ba46e1\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wishlist\` ADD CONSTRAINT \`FK_512bf776587ad5fc4f804277d76\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wishlist\` ADD CONSTRAINT \`FK_16f64e06715ce4fea8257cc42c5\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`wishlist\` DROP FOREIGN KEY \`FK_16f64e06715ce4fea8257cc42c5\``);
        await queryRunner.query(`ALTER TABLE \`wishlist\` DROP FOREIGN KEY \`FK_512bf776587ad5fc4f804277d76\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_a2cecd1a3531c0b041e29ba46e1\``);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` DROP FOREIGN KEY \`FK_55fa4db8406ed66bc7044328427\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_a922b820eeef29ac1c6800e826a\``);
        await queryRunner.query(`ALTER TABLE \`payment_transactions\` DROP FOREIGN KEY \`FK_0f581511ac19ecb02dab437cd41\``);
        await queryRunner.query(`ALTER TABLE \`order_status_history\` DROP FOREIGN KEY \`FK_1ca7d5228cf9dc589b60243933c\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_db2d0ea722e16e0fe8ab3bce111\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_145532db85752b29c57d2b7b1f1\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP FOREIGN KEY \`FK_6343513e20e2deab45edfce1316\``);
        await queryRunner.query(`ALTER TABLE \`inventory_logs\` DROP FOREIGN KEY \`FK_5132c139264f494991a44453746\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_ede780fc2b865d1d1323e598038\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_6385a745d9e12a89b859bb25623\``);
        await queryRunner.query(`ALTER TABLE \`carts\` DROP FOREIGN KEY \`FK_2ec1c94a977b940d85a4f498aea\``);
        await queryRunner.query(`ALTER TABLE \`variant_images\` DROP FOREIGN KEY \`FK_4006a994631d4bdb5938c831f39\``);
        await queryRunner.query(`ALTER TABLE \`variant_attribute_values\` DROP FOREIGN KEY \`FK_c714239ff4355d5e4dbfed5d196\``);
        await queryRunner.query(`ALTER TABLE \`variant_attribute_values\` DROP FOREIGN KEY \`FK_5df07e5f75117c9eca2c2ba5051\``);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` DROP FOREIGN KEY \`FK_be02d0f6a15bc7a0d835f832b62\``);
        await queryRunner.query(`ALTER TABLE \`attribute_value_images\` DROP FOREIGN KEY \`FK_873efe5d7f266ee50663fa68679\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_7d45aa29ba1109a087f0f6f19c2\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_5c9f4d5bfcfed501870842f8339\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_1530a6f15d3c79d1b70be98f2be\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_9a5f6868c96e0069e699f33e124\``);
        await queryRunner.query(`ALTER TABLE \`product_translations\` DROP FOREIGN KEY \`FK_1b7b07c6049367c6446c5ac5605\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_9482e9567d8dcc2bc615981ef44\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_728447781a30bc3fcfe5c2f1cdf\``);
        await queryRunner.query(`ALTER TABLE \`review_images\` DROP FOREIGN KEY \`FK_45b8671ec9f03b6682a52adb120\``);
        await queryRunner.query(`ALTER TABLE \`product_images\` DROP FOREIGN KEY \`FK_4f166bb8c2bfcef2498d97b4068\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_88cea2dc9c31951d06437879b40\``);
        await queryRunner.query(`ALTER TABLE \`category_translations\` DROP FOREIGN KEY \`FK_87902f79e775e1c1b0082201d7e\``);
        await queryRunner.query(`ALTER TABLE \`shipping_addresses\` DROP FOREIGN KEY \`FK_75ab21980cabc5be328df3e49cc\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_06792d0c62ce6b0203c03643cdd\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_b4599f8b8f548d35850afa2d12c\``);
        await queryRunner.query(`DROP INDEX \`IDX_d430a02aad006d8a70f3acd7d0\` ON \`role_permissions\``);
        await queryRunner.query(`ALTER TABLE \`inventory_logs\` CHANGE \`variant_id\` \`variant_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory_logs\` CHANGE \`reason\` \`reason\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` CHANGE \`variant_id\` \`variant_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` CHANGE \`cart_id\` \`cart_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`carts\` CHANGE \`user_id\` \`user_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`carts\` CHANGE \`guest_id\` \`guest_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`variant_images\` CHANGE \`variant_id\` \`variant_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`variant_attribute_values\` CHANGE \`attribute_value_id\` \`attribute_value_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`variant_attribute_values\` CHANGE \`variant_id\` \`variant_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`attribute_id\` \`attribute_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`attribute_value_images\` CHANGE \`attribute_value_id\` \`attribute_value_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`attribute_value_images\` CHANGE \`public_id\` \`public_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_attributes\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`gender_id\` \`gender_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`country_id\` \`country_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`category_id\` \`category_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`verifyToken\` \`verifyToken\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`productCode\` \`productCode\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`brand_id\` \`brand_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_translations\` CHANGE \`product_id\` \`product_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_translations\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reviews\` CHANGE \`product_id\` \`product_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reviews\` CHANGE \`user_id\` \`user_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reviews\` CHANGE \`comment\` \`comment\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`review_images\` CHANGE \`review_id\` \`review_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_images\` CHANGE \`product_id\` \`product_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`parent_id\` \`parent_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`slug\` \`slug\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category_translations\` CHANGE \`category_id\` \`category_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category_translations\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`shipping_addresses\` CHANGE \`user_id\` \`user_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`permissionId\` \`permissionId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`roleId\` \`roleId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`assignedBy\` \`assignedBy\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_d430a02aad006d8a70f3acd7d0\` ON \`role_permissions\` (\`roleId\`, \`permissionId\`)`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`DROP TABLE \`wishlist\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`user_sessions\``);
        await queryRunner.query(`DROP TABLE \`orders\``);
        await queryRunner.query(`DROP TABLE \`payment_transactions\``);
        await queryRunner.query(`DROP TABLE \`order_status_history\``);
        await queryRunner.query(`DROP TABLE \`order_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_46f236f21640f9da218a063a86\` ON \`product_variants\``);
        await queryRunner.query(`DROP TABLE \`product_variants\``);
    }

}
