server {
  listen 80;

  # NextJS - port 3000
  location / {
    proxy_pass http://next-app:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  # NestJS - port 5000
  location /api {
    proxy_pass http://nest-app:5000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}